Validators.required value with only whitespace
bietkul/react-reactive-form pull request #82
Opened 2022-05-13 09:16 UTC by arthurhamon

A control value with only whitespace should be considered empty.
Add a trim on the function that check for empty values.

2022-05-13 09:19 UTC, bietkul requested changes

2022-05-13 09:19 UTC, bietkul commented on src/validators.js
> +  return value == null || value.trim().length === 0
```suggestion
  return value == null || (typeof value === 'string' && value.trim().length === 0)
```

2022-05-13 11:50 UTC, arthurhamon commented
Request accepted :)

2022-05-13 12:19 UTC, arthurhamon commented
Can you merge it and create a new release ?

2022-05-23 08:29 UTC, arthurhamon commented
Hello @bietkul can we merge it ?

2023-02-04 18:30 UTC, bietkul approved these changes

2023-02-04 18:30 UTC, closed without merging